name: Chef

on:
  - pull_request

jobs:
  checks:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Bundle Install
      run: |
        gem install bundler:1.16.6
        bundle install --jobs 4 --retry 3
    - name: Rubocop
      run: |
        bundle exec rubocop --version
        bundle exec rubocop
    - name: Foodcritic
      run: |
        bundle exec foodcritic --version
        bundle exec foodcritic . --exclude spec
    - name: RSpec
      run: bundle exec rspec -f doc spec
