name: Supermarket

on:
  release:
    action: published

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Bundle Install
      run: |
        gem install bundler:1.16.6
        bundle install --jobs 4 --retry 3
    - name: Publish to Supermarket
      env:
        SUPERMARKET_PEM: ${{ secrets.SUPERMARKET_PEM }}
      run: >
        echo "${SUPERMARKET_PEM}" > supermarket.pem
        bundle exec knife supermarket share efs -o ..
          --config-option node_name=mkulka
          --config-option client_key=supermarket.pem
          -m https://supermarket.chef.io
